coverage:
  status:
    project:
      default:   # default is the status check's name, not default settings
        target: 90%
        threshold: 30% # these are rookie numbers.
        base: auto
        paths:
          - "src"
    patch:
        default:
            target: 90%
            base: auto
            paths:
            - "src"